version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: koolchaine_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - koolchaine_network

  backend:
    build: ./backend
    container_name: koolchaine_backend
    env_file:
      - .env
    volumes:
      - ./backend:/code
    depends_on:
      - db
    networks:
      - koolchaine_network

  frontend:
    build: ./frontend
    container_name: koolchaine_frontend
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    networks:
      - koolchaine_network



networks:
  koolchaine_network:
    driver: bridge

volumes:
  postgres_data:
