"""Add Shopify models

Revision ID: 031658e30df4
Revises: 2656778f6179
Create Date: 2026-03-02 17:40:06.159448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '031658e30df4'
down_revision: Union[str, Sequence[str], None] = '2656778f6179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopify_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shopify_id', sa.String(), nullable=False),
    sa.Column('order_number', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('shipping_address', sa.JSON(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('label_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('label_generated_at', sa.DateTime(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_index(op.f('ix_shopify_orders_id'), 'shopify_orders', ['id'], unique=False)
    op.create_index(op.f('ix_shopify_orders_shopify_id'), 'shopify_orders', ['shopify_id'], unique=True)
    op.create_table('stock_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('alerted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_alerts_id'), 'stock_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_stock_alerts_product_id'), 'stock_alerts', ['product_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_alerts_product_id'), table_name='stock_alerts')
    op.drop_index(op.f('ix_stock_alerts_id'), table_name='stock_alerts')
    op.drop_table('stock_alerts')
    op.drop_index(op.f('ix_shopify_orders_shopify_id'), table_name='shopify_orders')
    op.drop_index(op.f('ix_shopify_orders_id'), table_name='shopify_orders')
    op.drop_table('shopify_orders')
    # ### end Alembic commands ###
