"""add simulateur config and templates

Revision ID: 079e6a5950db
Revises: efe33a432edf
Create Date: 2026-03-05 14:02:35.505917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '079e6a5950db'
down_revision: Union[str, Sequence[str], None] = 'efe33a432edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulateur_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona', sa.String(), nullable=True),
    sa.Column('tarif_1_10', sa.Float(), nullable=True),
    sa.Column('tarif_11_30', sa.Float(), nullable=True),
    sa.Column('tarif_31_100', sa.Float(), nullable=True),
    sa.Column('tarif_101_200', sa.Float(), nullable=True),
    sa.Column('tarif_201_500', sa.Float(), nullable=True),
    sa.Column('tarif_500_plus', sa.Float(), nullable=True),
    sa.Column('cout_horaire_anim', sa.Float(), nullable=True),
    sa.Column('cout_materiel_par_pers', sa.Float(), nullable=True),
    sa.Column('cout_prestataires', sa.Float(), nullable=True),
    sa.Column('cout_personnalisation', sa.Float(), nullable=True),
    sa.Column('deplacement_type', sa.String(), nullable=True),
    sa.Column('deplacement_montant', sa.Float(), nullable=True),
    sa.Column('marge_pct', sa.Float(), nullable=True),
    sa.Column('option_prestataires', sa.Boolean(), nullable=True),
    sa.Column('option_deplacement', sa.Boolean(), nullable=True),
    sa.Column('option_materiel', sa.Boolean(), nullable=True),
    sa.Column('option_personnalisation', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona')
    )
    op.create_table('simulateur_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona', sa.String(), nullable=True),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('participants', sa.Integer(), nullable=True),
    sa.Column('duree', sa.String(), nullable=True),
    sa.Column('animateurs', sa.Integer(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('total_estime', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulateur_template')
    op.drop_table('simulateur_config')
    # ### end Alembic commands ###
