"""Add EmailTemplate and EmailLog tracking fields

Revision ID: 942c4fd06a62
Revises: b77c09d51fac
Create Date: 2026-03-03 18:44:35.632251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '942c4fd06a62'
down_revision: Union[str, Sequence[str], None] = 'b77c09d51fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_logs', sa.Column('tracking_id', sa.String(), nullable=True))
    op.add_column('email_logs', sa.Column('clicked_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_email_logs_tracking_id'), 'email_logs', ['tracking_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_logs_tracking_id'), table_name='email_logs')
    op.drop_column('email_logs', 'clicked_at')
    op.drop_column('email_logs', 'tracking_id')
    # ### end Alembic commands ###
