"""add prospection pipeline fields

Revision ID: a8988cb256d7
Revises: 079e6a5950db
Create Date: 2026-03-05 16:01:51.855664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8988cb256d7'
down_revision: Union[str, Sequence[str], None] = '079e6a5950db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraping_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('secteurs', sa.JSON(), nullable=True),
    sa.Column('effectifs_min', sa.Integer(), nullable=True),
    sa.Column('nb_societes_trouvees', sa.Integer(), nullable=True),
    sa.Column('nb_contacts_enrichis', sa.Integer(), nullable=True),
    sa.Column('nb_emails_generes', sa.Integer(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraping_jobs_id'), 'scraping_jobs', ['id'], unique=False)
    op.add_column('companies', sa.Column('secteur', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('effectifs', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('telephone', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('site_url', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('intent_levee_fonds', sa.Boolean(), nullable=True))
    op.add_column('companies', sa.Column('intent_salon', sa.Boolean(), nullable=True))
    op.add_column('companies', sa.Column('intent_recrutement_event', sa.Boolean(), nullable=True))
    op.add_column('companies', sa.Column('intent_score', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('intent_detail', sa.JSON(), nullable=True))
    op.add_column('companies', sa.Column('enriched_at', sa.DateTime(), nullable=True))
    op.add_column('contacts', sa.Column('email_source', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('email_confidence', sa.Float(), nullable=True))
    op.add_column('contacts', sa.Column('linkedin_url', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('score_pertinence', sa.Integer(), nullable=True))
    op.add_column('contacts', sa.Column('score_detail', sa.JSON(), nullable=True))
    op.add_column('contacts', sa.Column('email_genere', sa.Text(), nullable=True))
    op.add_column('contacts', sa.Column('email_valide', sa.Boolean(), nullable=True))
    op.add_column('contacts', sa.Column('enriched_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'enriched_at')
    op.drop_column('contacts', 'email_valide')
    op.drop_column('contacts', 'email_genere')
    op.drop_column('contacts', 'score_detail')
    op.drop_column('contacts', 'score_pertinence')
    op.drop_column('contacts', 'linkedin_url')
    op.drop_column('contacts', 'email_confidence')
    op.drop_column('contacts', 'email_source')
    op.drop_column('companies', 'enriched_at')
    op.drop_column('companies', 'intent_detail')
    op.drop_column('companies', 'intent_score')
    op.drop_column('companies', 'intent_recrutement_event')
    op.drop_column('companies', 'intent_salon')
    op.drop_column('companies', 'intent_levee_fonds')
    op.drop_column('companies', 'site_url')
    op.drop_column('companies', 'telephone')
    op.drop_column('companies', 'effectifs')
    op.drop_column('companies', 'secteur')
    op.drop_index(op.f('ix_scraping_jobs_id'), table_name='scraping_jobs')
    op.drop_table('scraping_jobs')
    # ### end Alembic commands ###
