"""enrich prospection models

Revision ID: da7153ac5a5a
Revises: a8988cb256d7
Create Date: 2026-03-06 15:53:38.195187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da7153ac5a5a'
down_revision: Union[str, Sequence[str], None] = 'a8988cb256d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_assets')
    op.add_column('companies', sa.Column('code_naf', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('site_web', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('ville', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('code_postal', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('statut', sa.String(), nullable=True))
    op.alter_column('scraping_jobs', 'log',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               postgresql_using='log::json',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scraping_jobs', 'log',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('companies', 'statut')
    op.drop_column('companies', 'code_postal')
    op.drop_column('companies', 'ville')
    op.drop_column('companies', 'site_web')
    op.drop_column('companies', 'code_naf')
    op.create_table('media_assets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('filepath', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_favorite', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('persona', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tags_auto', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tags_manual', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('visual_fiche', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('claude_analysis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('captions_generated', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('analyzed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('media_assets_pkey'))
    )
    # ### end Alembic commands ###
