"""add sandbox history and tone of voice

Revision ID: efe33a432edf
Revises: d89c6cd579cc
Create Date: 2026-03-05 09:57:24.810915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe33a432edf'
down_revision: Union[str, Sequence[str], None] = 'd89c6cd579cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tone_of_voice_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona', sa.String(), nullable=False),
    sa.Column('brand_identity', sa.String(), nullable=True),
    sa.Column('words_to_use', sa.JSON(), nullable=True),
    sa.Column('words_forbidden', sa.JSON(), nullable=True),
    sa.Column('style_references', sa.JSON(), nullable=True),
    sa.Column('topics_to_avoid', sa.JSON(), nullable=True),
    sa.Column('default_tone', sa.String(), nullable=True),
    sa.Column('default_length', sa.String(), nullable=True),
    sa.Column('default_emojis', sa.String(), nullable=True),
    sa.Column('default_hashtag_count', sa.Integer(), nullable=True),
    sa.Column('default_language', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona')
    )
    op.create_table('sandbox_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(), nullable=True),
    sa.Column('persona', sa.String(), nullable=True),
    sa.Column('brief', sa.String(), nullable=True),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('variants', sa.JSON(), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sandbox_history')
    op.drop_table('tone_of_voice_config')
    # ### end Alembic commands ###
